const products = [
  {
    id: 1,
    title: 'Samsung Galaxy S23 Ultra',
    category: 'phone',
    price: 81990,
    featureImg: './img/smartPhone/cp-1.jpg',
    imgs: ['./img/smartPhone/cp-1.jpg', './img/smartPhone/cp-2.jpg', './img/smartPhone/cp-3.jpg', './img/smartPhone/cp-4.jpg', './img/smartPhone/cp-5.jpg', './img/smartPhone/cp-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 2,
    title: 'HUAWEI WATCH GT 3',
    category: 'watch',
    price: 8990.0,
    featureImg: './img/smartWatch/sw-1.jpg',
    imgs: ['./img/smartWatch/sw-1.jpg', './img/smartWatch/sw-2.jpg', './img/smartWatch/sw-3.jpg', './img/smartWatch/sw-4.jpg', './img/smartWatch/sw-5.jpg', './img/smartWatch/sw-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 3,
    title: 'SAMSUNG 50-INCH 4K',
    category: 'tv',
    price: 8990.0,
    featureImg: './img/smartTv/st-1.jpg',
    imgs: ['./img/smartTv/st-1.jpg', './img/smartTv/st-2.jpg', './img/smartTv/st-3.jpg', './img/smartTv/st-4.jpg', './img/smartTv/st-5.jpg', './img/smartTv/st-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 4,
    title: 'Apple MacBook Air',
    category: 'laptop',
    price: 82990.0,
    featureImg: './img/laptop/lt-1.jpg',
    imgs: ['./img/laptop/lt-1.jpg', './img/laptop/lt-2.jpg', './img/laptop/lt-3.jpg', './img/laptop/lt-4.jpg', './img/laptop/lt-5.jpg', './img/laptop/lt-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 5,
    title: 'NZXT T120 CPU Air Cooler',
    category: 'computer',
    price: 915.0,
    featureImg: './img/airCooler/ac-1.png',
    imgs: ['./img/airCooler/ac-1.png', './img/airCooler/ac-2.jpg', './img/airCooler/ac-3.jpg', './img/airCooler/ac-4.jpg', './img/airCooler/ac-5.jpg', './img/airCooler/ac-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 6,
    title: 'Home Security Camera',
    category: 'camera',
    price: 10462.0,
    featureImg: './img/cctv/oc-1.png',
    imgs: ['./img/cctv/oc-1.png', './img/cctv/oc-2.jpg', './img/cctv/oc-3.jpg', './img/cctv/oc-4.jpg', './img/cctv/oc-5.jpg', './img/cctv/oc-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 7,
    title: 'Beats Studio Pro',
    category: 'headphones',
    price: 10462.0,
    featureImg: './img/headPhones/hp-1.png',
    imgs: ['./img/headPhones/hp-1.png', './img/headPhones/hp-2.jpg', './img/headPhones/hp-3.jpg', './img/headPhones/hp-4.jpg', './img/headPhones/hp-5.jpg', './img/headPhones/hp-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 8,
    title: 'Anne Pro2 Mini',
    category: 'keyboard',
    price: 4550.0,
    featureImg: './img/keyboard/kb-1.jpg',
    imgs: ['./img/keyboard/kb-1.jpg', './img/keyboard/kb-2.jpg', './img/keyboard/kb-3.jpg', './img/keyboard/kb-4.jpg', './img/keyboard/kb-5.jpg', './img/keyboard/kb-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 9,
    title: 'JBL Wireless speaker',
    category: 'speaker',
    price: 2399.0,
    featureImg: './img/speaker/ws-1.jpg',
    imgs: ['./img/speaker/ws-1.jpg', './img/speaker/ws-2.jpg', './img/speaker/ws-3.jpg', './img/speaker/ws-4.jpg', './img/speaker/ws-5.jpg', './img/speaker/ws-6.jpg'],
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
]
