const products = [
  {
    id: 1,
    title: 'Samsung Galaxy S23 Ultra',
    category: 'phone',
    price: 81990,
    featureImg: './img/smartPhone/cp-1.jpg',
    imgs: ['./img/smartPhone/cp-1.jpg', './img/smartPhone/cp-2.jpg', './img/smartPhone/cp-3.jpg', './img/smartPhone/cp-4.jpg', './img/smartPhone/cp-5.jpg', './img/smartPhone/cp-6.jpg'],
    desc: "The Samsung Galaxy S23 Ultra is a flagship smartphone that combines cutting-edge technology with stunning design. Featuring a high-resolution AMOLED display, powerful processing capabilities, and a versatile camera system, it offers an exceptional user experience. With 5G connectivity, ample storage options, and a sleek, premium build, the Galaxy S23 Ultra is a top choice for those seeking a feature-packed and stylish mobile device.",
  },
  {
    id: 2,
    title: 'HUAWEI WATCH GT 3',
    category: 'watch',
    price: 8990.0,
    featureImg: './img/smartWatch/sw-1.jpg',
    imgs: ['./img/smartWatch/sw-1.jpg', './img/smartWatch/sw-2.jpg', './img/smartWatch/sw-3.jpg', './img/smartWatch/sw-4.jpg', './img/smartWatch/sw-5.jpg', './img/smartWatch/sw-6.jpg'],
    desc: "The HUAWEI WATCH GT 3 is a sleek and advanced smartwatch that combines elegant design with cutting-edge technology. With a vibrant AMOLED display, it offers a wide range of health and fitness features, including heart rate monitoring, sleep tracking, and GPS tracking for outdoor activities.",
  },
  {
    id: 3,
    title: 'SAMSUNG 50-INCH 4K',
    category: 'tv',
    price: 8990.0,
    featureImg: './img/smartTv/st-1.jpg',
    imgs: ['./img/smartTv/st-1.jpg', './img/smartTv/st-2.jpg', './img/smartTv/st-3.jpg', './img/smartTv/st-4.jpg', './img/smartTv/st-5.jpg', './img/smartTv/st-6.jpg'],
    desc: "The Samsung 50-inch 4K TV offers stunning picture quality with its ultra-high-definition resolution, providing sharp and vibrant visuals. Its generous screen size immerses you in your favorite movies, shows, and games, while smart features allow for easy streaming and access to a world of entertainment. Experience cinematic clarity and convenience with this impressive 4K television from Samsung.",
  },
  {
    id: 4,
    title: 'Apple MacBook Air',
    category: 'laptop',
    price: 82990.0,
    featureImg: './img/laptop/lt-1.jpg',
    imgs: ['./img/laptop/lt-1.jpg', './img/laptop/lt-2.jpg', './img/laptop/lt-3.jpg', './img/laptop/lt-4.jpg', './img/laptop/lt-5.jpg', './img/laptop/lt-6.jpg'],
    desc: "The Apple MacBook Air is an ultraportable laptop renowned for its sleek design, lightweight construction, and impressive performance. It features a stunning Retina display, a comfortable keyboard, and the power of Apple's M1 chip, making it an ideal choice for those seeking a blend of style, portability, and computing prowess.",
  },
  {
    id: 5,
    title: 'NZXT T120 CPU Air Cooler',
    category: 'computer',
    price: 915.0,
    featureImg: './img/airCooler/ac-1.png',
    imgs: ['./img/airCooler/ac-1.png', './img/airCooler/ac-2.jpg', './img/airCooler/ac-3.jpg', './img/airCooler/ac-4.jpg', './img/airCooler/ac-5.jpg', './img/airCooler/ac-6.jpg'],
    desc: "The NZXT T120 CPU Air Cooler is a high-performance cooling solution designed to keep your computer's processor running efficiently. With its sleek and modern design, it not only provides excellent thermal performance but also adds a touch of style to your PC build. Its robust cooling capabilities ensure that your CPU remains at optimal temperatures, allowing for smoother and quieter operation even during intense tasks.",
  },
  {
    id: 6,
    title: 'D-Link DCS-2670L',
    category: 'camera',
    price: 10462.0,
    featureImg: './img/cctv/oc-1.png',
    imgs: ['./img/cctv/oc-1.png', './img/cctv/oc-2.jpg', './img/cctv/oc-3.jpg', './img/cctv/oc-4.jpg', './img/cctv/oc-5.jpg', './img/cctv/oc-6.jpg'],
    desc: "The D-Link DCS-2670L is a high-definition outdoor Wi-Fi camera designed for home and business security. It offers sharp 1080p video quality, robust weatherproof construction, and remote monitoring capabilities through a mobile app. With features like motion detection and night vision, it provides reliable surveillance and peace of mind, even in challenging outdoor conditions.",
  },
  {
    id: 7,
    title: 'Beats Studio Pro',
    category: 'headphones',
    price: 10462.0,
    featureImg: './img/headPhones/hp-1.png',
    imgs: ['./img/headPhones/hp-1.png', './img/headPhones/hp-2.jpg', './img/headPhones/hp-3.jpg', './img/headPhones/hp-4.jpg', './img/headPhones/hp-5.jpg', './img/headPhones/hp-6.jpg'],
    desc: "The Beats Studio Pro is a premium wireless headphone model known for its exceptional audio quality, active noise cancellation, and sleek, modern design. These headphones offer an immersive listening experience with deep bass and crisp highs, making them ideal for music enthusiasts and professionals seeking high-performance audio.",
  },
  {
    id: 8,
    title: 'Anne Pro2 Mini',
    category: 'keyboard',
    price: 4550.0,
    featureImg: './img/keyboard/kb-1.jpg',
    imgs: ['./img/keyboard/kb-1.jpg', './img/keyboard/kb-2.jpg', './img/keyboard/kb-3.jpg', './img/keyboard/kb-4.jpg', './img/keyboard/kb-5.jpg', './img/keyboard/kb-6.jpg'],
    desc: "The Anne Pro 2 Mini is a compact and versatile mechanical keyboard designed for enthusiasts and professionals. With a small form factor, wireless connectivity, customizable RGB backlighting, and hot-swappable switches, it offers a highly customizable and portable typing experience.",
  },
  {
    id: 9,
    title: 'JBL Wireless speaker',
    category: 'speaker',
    price: 2399.0,
    featureImg: './img/speaker/ws-1.jpg',
    imgs: ['./img/speaker/ws-1.jpg', './img/speaker/ws-2.jpg', './img/speaker/ws-3.jpg', './img/speaker/ws-4.jpg', './img/speaker/ws-5.jpg', './img/speaker/ws-6.jpg'],
    desc: "The JBL Wireless Speaker is a sleek and portable audio device that delivers exceptional sound quality without the hassle of wires. With its modern design, impressive battery life, and easy connectivity to your devices, it's the perfect companion for on-the-go music enthusiasts, providing a rich and immersive listening experience wherever you are.",
  },
  {
    id: 10,
    title: 'LG G7 ThinQ',
    category: 'phone',
    price: 18000,
    featureImg: './img/smartPhone2/phone3.jpg',
    imgs: ['./img/smartPhone2/phone3.jpg', './img/smartPhone2/phone2.jpg', './img/smartPhone2/phone1.jpg'],
    desc: "The LG G7 ThinQ is a stylish and feature-packed smartphone known for its vibrant 6.1-inch QHD+ display, powerful performance, and advanced camera capabilities. With AI-enhanced features, it delivers impressive photography results and includes features like Super Bright Display and Boombox Speaker for an immersive multimedia experience.",
  },
  {
    id: 11,
    title: 'V380 Pro 1080p',
    category: 'camera',
    price: 2529.0,
    featureImg: './img/cctv2/cam3.jpg',
    imgs: ['./img/cctv2/cam3.jpg', './img/cctv2/cam2.jpg', './img/cctv2/cam1.png'],
    desc: "The V380 Pro 1080p is a high-quality surveillance camera that offers crisp 1080p video resolution, making it ideal for monitoring your home or office. With its advanced features and easy-to-use interface, it provides reliable security and peace of mind.",
  },
  {
    id: 12,
    title: 'Oppo Band 2',
    category: 'watch',
    price: 2529.0,
    featureImg: './img/smartWatch2/watch3.jpg',
    imgs: ['./img/smartWatch2/watch3.jpg', './img/smartWatch2/watch2.jpg', './img/smartWatch2/watch1.jpg'],
    desc: "The HUAWEI WATCH GT 3 is a sleek and advanced smartwatch that combines elegant design with cutting-edge technology. With a vibrant AMOLED display, it offers a wide range of health and fitness features, including heart rate monitoring, sleep tracking, and GPS tracking for outdoor activities.",
  },
  {
    id: 13,
    title: 'Haier H65K68UG',
    category: 'tv',
    price: 32393.0,
    featureImg: './img/smartTv2/tv3.jpg',
    imgs: ['./img/smartTv2/tv3.jpg', './img/smartTv2/tv2.jpg', './img/smartTv2/tv1.jpg'],
    desc: "The Haier H65K68UG is a cutting-edge 65-inch 4K UHD Smart TV powered by Android 11. It offers stunning picture quality with vivid 4K resolution, while its smart features provide seamless access to a world of entertainment and apps. This TV combines sleek design with advanced technology for an immersive viewing experience.",
  },
  {
    id: 14,
    title: 'ASUS ROG Ryujin III',
    category: 'computer',
    price: 21374.0,
    featureImg: './img/airCooler2/cooler3.jpg',
    imgs: ['./img/airCooler2/cooler3.jpg', './img/airCooler2/cooler2.jpg', './img/airCooler2/cooler1.png'],
    desc: "The ASUS ROG Ryujin III is a high-performance all-in-one liquid CPU cooler designed for gamers and enthusiasts. It features a sleek and stylish design with customizable RGB lighting, providing both aesthetics and cooling efficiency.",
  },
  {
    id: 15,
    title: 'Divoom Mocha',
    category: 'speaker',
    price: 6950.0,
    featureImg: './img/speaker2/speaker1.jpg',
    imgs: ['./img/speaker2/speaker1.jpg', './img/speaker2/speaker2.jpg', './img/speaker2/speaker3.jpg'],
    desc: "The Divoom Mocha is a stylish and compact portable speaker that combines excellent audio quality with a trendy design. Its sleek and coffee-inspired appearance makes it a fashionable accessory for any coffee lover. With Bluetooth connectivity, long battery life, and customizable LED lights, it's perfect for enjoying your favorite music while adding a touch of style to your space.",
  },
  {
    id: 16,
    title: 'HP Spectre x360',
    category: 'laptop',
    price: 101576.0,
    featureImg: './img/laptop2/laptop3.jpg',
    imgs: ['./img/laptop2/laptop3.jpg', './img/laptop2/laptop2.jpg', './img/laptop2/laptop1.jpg'],
    desc: "The HP Spectre x360 14-ef0069TU is a sleek and powerful 2-in-1 laptop featuring a 14-inch display. It's powered by an Intel Core i7 processor and equipped with 16GB of RAM for smooth multitasking. With a choice of either a 512GB or 1TB storage option, you'll have ample space for your files and applications.",
  },
  {
    id: 17,
    title: 'Audio-Technica',
    category: 'headphones',
    price: 7499.0,
    featureImg: './img/headPhones2/headphones3.jpg',
    imgs: ['./img/headPhones2/headphones3.jpg', './img/headPhones2/headphones2.jpg', './img/headPhones2/headphones2.jpg'],
    desc: "The Audio-Technica ATH-SR30BT is a high-quality wireless headphones with a sleek design, delivering an impressive audio experience. With Bluetooth connectivity and a comfortable fit, these headphones are perfect for on-the-go music lovers seeking a balanced sound and extended listening sessions.",
  },
  {
    id: 18,
    title: 'Asus ROG Azoth',
    category: 'keyboard',
    price: 13495.0,
    featureImg: './img/keyboard2/keyboard1.jpg',
    imgs: ['./img/keyboard2/keyboard1.jpg', './img/keyboard2/keyboard2.jpg', './img/keyboard2/keyboard3.jpg'],
    desc: "The Asus ROG Azoth Gaming Custom Hotswappable Mechanical Keyboard is a high-performance gaming keyboard designed for enthusiasts. Featuring customizable hotswappable switches, this keyboard allows you to tailor your typing and gaming experience to your preference.",
  },
]


export default products
